language: node_js
node_js:
  - "stable"
services:
  - "mongodb"
cache:
  directories:
    - "node_modules"
before_install:
  - "npm install"
after_success:
  - "npm run coverage"
script:
  - "npm run travistest"